DROP TABLE IF EXISTS trips;

CREATE TABLE trips (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	route_id TEXT,
	service_id TEXT,
	trip_id TEXT,
	trip_headsign TEXT,
	trip_short_name TEXT,
	direction_id TEXT,
	block_id TEXT,
	shape_id TEXT,
	wheelchair_accessible TEXT,
	bikes_allowed TEXT
};
